#
# Module manifest for module 'Pode.Game'
#
# Generated by: Matthew Kelly (Badgerati)
#
# Generated on: 11/12/2021
#

@{
    # Script module or binary module file associated with this manifest.
    RootModule = 'Pode.Game.psm1'

    # Version number of this module.
    ModuleVersion = '0.1.0'

    # ID used to uniquely identify this module
    GUID = '585480e5-c876-450d-a347-fa3372a2a7e5'

    # Author of this module
    Author = 'Matthew Kelly (Badgerati)'

    # Copyright statement for this module
    Copyright = 'Copyright (c) 2021 Matthew Kelly (Badgerati), licensed under the MIT License.'

    # Description of the functionality provided by this module
    Description = 'Game framework for use with the Pode PowerShell web server'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.0'

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{
        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('powershell', 'game', 'server', 'pode', 'framework', '2d')

            # A URL to the license for this module.
            LicenseUri = 'https://raw.githubusercontent.com/Badgerati/Pode.Game/master/LICENSE.txt'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/Badgerati/Pode.Game'

            # A URL to an icon representing this module.
            IconUri = 'https://raw.githubusercontent.com/Badgerati/Pode.Game/master/images/icon.png'

        }
    }
}